---
- name: Instalar dependencias base para Slurm y Munge
  apt:
    name:
      - slurm-wlm
      - munge
      - libmunge-dev
      - libmunge2
      - build-essential
    state: present
    update_cache: yes

- name: Asegurar que el usuario "slurm" existe
  user:
    name: slurm
    shell: /bin/false
    system: yes

- name: Crear directorio de configuración de Slurm si no existe
  file:
    path: /etc/slurm-llnl
    state: directory
    mode: '0755'
  become: true


- name: Copiar configuración Slurm
  template:
    src: slurm.conf.j2
    dest: /etc/slurm-llnl/slurm.conf
    owner: root
    group: root
    mode: 0644
  notify: Reiniciar Slurm

- name: Iniciar y habilitar munge
  service:
    name: munge
    state: started
    enabled: yes

- name: Iniciar y habilitar slurmctld (solo si es controlador)
  service:
    name: slurmctld
    state: started
    enabled: yes
  when: inventory_hostname in groups['slurm_controller']

- name: Iniciar y habilitar slurmd (solo si es nodo de cómputo)
  service:
    name: slurmd
    state: started
    enabled: yes
  when: inventory_hostname in groups['slurm_nodes']

- name: Instalar agente Checkmk
  copy:
    src: check-mk-agent_2.3.0p34-1_all.deb
    dest: /tmp/checkmk-agent.deb

- name: Instalar paquete Checkmk
  apt:
    deb: /tmp/checkmk-agent.deb
